---
name: AnimalCoins
version: 0.0.1
main: dpgenx\animalcoins\AnimalCoins
api: 4.0.0
commands:
  animalcoins:
    permission: animalcoins.cmd
    description: "About of Animal Coins"
permissions:
  animalcoins.cmd:
    default: op
...
